# Generated by Django 4.2.14 on 2024-08-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='licence_data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='licence_data',
            name='pdf',
            field=models.FileField(upload_to='documents'),
        ),
    ]
