# Generated by Django 4.2.15 on 2024-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence_app', '0003_delete_user_alter_licence_data_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence_data',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('USER', 'USER')], default='USER', max_length=10),
        ),
    ]
