# Generated by Django 4.2.15 on 2024-08-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licence_app', '0004_licence_data_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence_data',
            name='user_type',
        ),
    ]
